---
- name: Touch file
  file:
    path: /etc/pip.conf
    state: touch

- name: Adding pip.conf Key
  blockinfile:
    path: /etc/pip.conf
    content: |
      [global]
      extra-index-url=https://bright:TheFutureBank2030@pypi.brightmoney.co/simple
                      https://bright:TheFutureBank2030@pypi.brightmoney.co/snapshots/simple