---
- name: Install EC2 Connect
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 3600
    name: "ec2-instance-connect"
    state: present
  register: ec2connect_status
  until: ec2connect_status is success
  delay: 6
  retries: 10
