---
- hosts: localhost
  gather_facts: false
  vars_files:
      - base_lts.yml
      - ec2_vars.yml
  tasks:
  - name: Gather information about Ubuntu 18.04 AMIs
    amazon.aws.ec2_ami_info:
      owners: 294639299176 
      filters:
        name: "{{ ami_name }}"
    register: ec2_ami

  # - debug:
  #     msg: "{{ ec2_ami.images[0].image_id }}" 

  - name: Create an instance
    include_role:
      name: "../../../roles/ec2"
    vars:
      ami_id: "{{ ec2_ami.images[0].image_id }}"
      instance_name: "{{ item.name }}"
      instance_component: "{{ item.component }}"
      instance_type: "{{ item.instance_type }}"
    with_items: "{{ instances }}"
      
# - hosts: hyperion-dev
#   strategy: free
#   vars_files:
#       - ec2_vars.yml
#       - filebeat_vars.yml
#   become: false
#   tasks:
#   - name: Set up an instances
#     include_role:
#       name: "../../../roles/ec2_setup"

#   # - name: Install Ossec
#   #   include_role:
#   #     name: "../../../roles/ossec"

#   - name: Configure filebeat
#     include_role:
#       name: "../../../roles/filebeat"
