---
- name: Download statsd exporter
  get_url:
    url: "{{ statsd_exporter_url }}"
    dest: "{{ statsd_download_path }}"

- name: Extract Statsd tar.gz
  ansible.builtin.unarchive:
    remote_src: yes
    src: "{{ statsd_download_path }}"
    dest: "{{ statsd_extraction_dest }}"

- name: Move executable to bin
  become: true
  command: "mv {{statsd_extraction_dest}}/{{statsd_exporter_package}}/statsd_exporter {{usr_bin_dir}}/statsd_exporter"

- name: Create a directory if it does not exist
  become: true
  file:
    path: "{{ statsd_config_dir }}"
    state: directory

- name: Ensure the user 'prometheus'
  become: true
  user:
    name: prometheus
    state: present
    system: yes
    shell: /bin/bash

- name: Copy Stasd exporter config file
  become: true
  template:
    src: statsd_mapping.j2
    dest: "{{ statsd_config_dir }}/{{ statsd_config_file_name }}"

- name: Copy Statsd exporter service file
  become: true
  template:
    src: statsd_exporter_service.j2
    dest: /etc/systemd/system/statsd_exporter.service

- name: force systemd to reread configs
  become: true
  systemd: daemon_reload=yes

- name: Start service statsd_exporter
  become: true
  systemd:
    name: statsd_exporter
    state: started

- name: enable service statsd_exporter
  become: true
  systemd:
    name: statsd_exporter
    enabled: yes

- name: Make sure a service is running
  become: true
  systemd:
    state: started
    name: statsd_exporter



