
- hosts: localhost
  vars_files:
      - ec2_vars.yml
  tasks:
  - name: Gather information about {{ ami_name }} AMIs
    amazon.aws.ec2_ami_info:
      owners: 294639299176 
      filters:
        name: "{{ami_name}}"
    register: ec2_ami

  - name: Create an instance
    include_role:
      name: "../../../roles/ec2"
    vars:
      ami_id: "{{ ec2_ami.images[-1].image_id }}"
      instance_name: "{{ item }}"
    with_items: "{{ instances }}"
      
- hosts: firestore-dev
  vars_files:
      - ec2_vars.yml
      - filebeat_vars.yml
  become: yes
  tasks:
  - name: Set up an instances
    include_role:
      name: "../../../roles/ec2_setup"

  # - name: Install Ossec
  #   include_role:
  #     name: "../../../roles/ossec"
