---

- name: "Download nginx exporter"
  get_url:
    url: "{{nginx_exporter_url}}"
    dest: "{{nginx_download_path}}"

- name: Extract nginx_exporter tar.gz into 
  ansible.builtin.unarchive:
    remote_src: yes
    src: "{{nginx_download_path}}"
    dest: "{{ nginx_extraction_dest }}"

- name: Move executable to bin
  command: "sudo mv {{nginx_extraction_dest}}/nginx-prometheus-exporter {{usr_bin_dir}}/nginx-prometheus-exporter"

- name: Copy nginx exporter service file
  ansible.builtin.template:
    src: nginx_exporter_service.j2
    dest: /etc/systemd/system/nginx_exporter.service

- name: Force systemd to reread configs
  systemd: daemon_reload=yes

- name: Start service nginx_exporter
  systemd:
    name: nginx_exporter
    state: started

- name: enable service nginx_exporter
  systemd:
    name: nginx_exporter
    enabled: yes

- name: Make sure a service is running
  systemd:
    state: started
    name: nginx_exporter

- name: Update Brightmoney nginx logrotation
  ansible.builtin.template:
    src: logrotate.d/bright_nginx
    dest: /etc/logrotate.d/bright_nginx
