---

- name: Create Ec2 instance
  include_tasks: ec2_create_with_add_volume.yml
  when: additional_volume_needed

- name: Create EC2 instance without additional volume
  include_tasks: ec2_without_volume.yml
  when: not additional_volume_needed
